project_id = "rqrhavvtkgvnsjccywye"

[functions.chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.process-file]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false
